# Generated by Django 3.1.5 on 2021-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_auto_20210110_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaimagem',
            name='is_segmentada',
            field=models.BooleanField(default=False, verbose_name='A imagem está segmentada'),
        ),
    ]
