# Generated by Django 3.1.5 on 2021-01-21 00:09

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagens', '0004_metaimagem_porosidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='VER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_ver', jsonfield.fields.JSONField(default=dict)),
                ('meta_imagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imagens.metaimagem', verbose_name='meta_imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
