# Generated by Django 3.1.5 on 2021-01-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0005_metaimagem_resolucao'),
        ('fisicadigital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permeabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('permeabilidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meta_imagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imagens.metaimagem', verbose_name='meta_imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
